syntax = "proto3";

package adlabel.mapping;

enum CameraType {
  CAMERA_TYPE_UNKNOWN = 0;
  CAMERA_TYPE_PINHOLE = 1;  // OpenCV pinhole model: [k1, k2, p1, p2, k3].
  CAMERA_TYPE_FISHEYE = 2;  // OpenCV fisheye model: [k1, k2, k3, k4].
}

message CameraCalibration {
  optional CameraType camera_type = 1;
  // camera intrinsics, either stored as a 4 vector (fx, fy, cx, cy)
  // or a 3x3 row major matrix, in case to handle skew factor
  repeated double intrinsics = 2;
  // pinhole: [k1, k2, p1, p2] or [k1, k2, p1, p2, k3]
  // fisheye: [k1, k2, k3, k4]
  repeated double distortion_coefficients = 3;
  optional uint32 width = 4;
  optional uint32 height = 5;
}
