syntax = "proto3";

package adlabel.mapping;

import "mapping/protos/pose.proto";
import "mapping/protos/camera_calibration.proto";

message Frame {
  optional string trip_id = 1;   
  optional string fid = 2;
  optional string prev_id = 3;
  optional string next_id = 4;
  optional int64 timestamp_ns = 5;

  enum SensorType {
    UNKNOWN = 0;
    LIDAR   = 1;
    CAMERA  = 2;
    RADAR   = 3;
  }

  optional SensorType sensor_type = 6;
  optional string   sensor_name = 7;  

  // data uri
  optional string cloud_uri = 8;
  optional string camera_image_uri = 9;
  optional string lidar_object_detection_uri = 10; // in imu coordinate
  optional string lidar_nn_uri = 17;

  // localization related
  optional Pose3DMessage gnss_pose_3d = 11;
  optional Pose3DMessage lio_pose_3d = 12;
  optional Pose3DMessage refined_pose_3d = 16;

  // extrinsic
  optional Pose3DMessage sensor_to_imu_extrinsic = 13;

  // camera_related
  optional CameraCalibration camera_calibration = 14;
  optional string camera_segmentation_uri = 15;
}
